### ISSUE TITLE
 Target class [cache] does not exist.

### ISSUE THREAD

**Issue by afzelarshad** [liberu-ecommerce/ecommerce-laravel#137]
This is  a **bug**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

### Description

My php verstion is 8.3
and i'm using ubuntu 22.04

### Steps to Reproduce
1. when i run setup.sh script in new project
2. it shows this error in terminal
3. it still shows this error on every php artisan cli command

![Screenshot from 2024-06-12 13-32-00](https://github.com/liberu-ecommerce/ecommerce-laravel/assets/49970920/f751268e-f91a-422a-a0f6-fd3cf91b8af1)

**Comment by curtisdelicata** [comment]
Now fixed.
