### ISSUE TITLE
Hard to install, many errors 

### ISSUE THREAD

**Issue by geimsdin** [liberu-ecommerce/ecommerce-laravel#142]
### Details
1 - Migrations order is wrong, dependant tables are created before their dependency causing an error
2 - Migrations content has duplicated foreign keys
3 - Text encoding is wrong and many php files have the php opening tag converted in html making the file unreadable
4 - Some public functions are outside the class causing a fatal error

**Comment by geimsdin** [comment]
You removed the foreign keys reference and cascade, the correct fix for database/migrations/2023_09_30_151612_create_invoices_table.php is probably this:
 $table->foreignId('customer_id')->constrained()->references('id')->on('orders')->onDelete('cascade');
 $table->foreignId('order_id')->constrained()->references('id')->on('customers')->onDelete('cascade');

This issue doesn't seem to be resolved:
Fix the text encoding issues in PHP files where the PHP opening tag is converted to HTML

**Comment by curtisdelicata** [comment]
We are looking for pull requests. Thank you for reporting this issues



We are slowly working through all projects failing, plus testing.

**Comment by curtisdelicata** [comment]
@geimsdin

**Comment by curtisdelicata** [comment]
I've fixed migrations and install.yml now passes @geimsdin

**Comment by curtisdelicata** [comment]
Please verify my sweep and manual changes. Install now seems to work.
